import type { Metadata } from "next";

import "@repo/ui/globals.css";
import { cn } from "@repo/ui/lib/utils";
import { inter } from "./fonts";
import MainNav from "@/components/MainNav";
import Footer from "@/components/Footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.variable)}>
        <MainNav />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
