import type { Metadata } from "next";
import "@repo/ui/globals.css";
import MainNav from "@repo/ui/components/main-nav";
import { cn } from "@repo/ui/lib/utils";
import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn(inter.variable, "antialiased")}>
        <MainNav />
        <main>{children}</main>
      </body>
    </html>
  );
}
